name: "Build the images"

on:
  workflow_dispatch:
  pull_request:

jobs:
  run_action:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Build Image
        uses: ./.
        with:
          armbian_board: renegade
          armbian_release: questing
          armbian_target: image
